project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: http://robertilyes.github.io # you must change this appropriately for RSS feeds to work properly
  title: "Robertilyes.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



